plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'Rakefile'
    - 'config/**/*'
    - 'vendor/**/*'

  NewCops: enable

  TargetRailsVersion: 8.0
  TargetRubyVersion: 3.4

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
  Max: 35

Metrics/MethodLength:
  Max: 15

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
