# https://github.com/m4rcelotoledo/Dockerfiles
# https://hub.docker.com/repository/docker/skygvinn/alpine3-ruby2.7-nodejs

version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  server:
    image: skygvinn/alpine3-ruby2.7-nodejs:v1.0
    container_name: bank_accounting
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=vendor/bundle
      - BUNDLE_DISABLE_SHARED_GEMS=1
      - RUBYOPT=-W0
    volumes:
      - .:/var/www/bank_accounting:Z
    working_dir: /var/www/bank_accounting
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - db
