services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  server:
    image: ruby:3.4.6-alpine
    container_name: bank_accounting
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=vendor/bundle
      - BUNDLE_DISABLE_SHARED_GEMS=1
      - RUBYOPT=-W0
    volumes:
      - .:/var/www/bank_accounting:Z
    working_dir: /var/www/bank_accounting
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - db
